version: '3'
services:
        db:
                build: .
                ports:
                        - "1433:1433"
                environment:
                        - ACCEPT_EULA=Y
                        - SA_PASSWORD=P@ssword1
